services:
  # 1. Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: toolrent-db
    environment:
      - POSTGRES_DB=toolrent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - toolrent-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Keycloak (Servidor de Identidad)
  keycloak:
      image: quay.io/keycloak/keycloak:24.0.1
      container_name: toolrent-keycloak
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      # IMPORTANTE: Le decimos que importe el archivo al arrancar
      command: start-dev --import-realm
      ports:
        - "8090:8080"
      networks:
        - toolrent-net
      # IMPORTANTE: Conectamos tu archivo JSON al contenedor
      volumes:
        - ./keycloak-data/realm-export.json:/opt/keycloak/data/import/realm.json
      depends_on:
        db:
          condition: service_healthy

# 3. Backend (Spring Boot) - ¡COMENTAR TODO ESTO!
  # Razón: Lo correrás en tu IDE (IntelliJ) o terminal con './mvnw spring-boot:run'
  # Si no lo comentas, Docker ocupará el puerto 8080 y tu IDE fallará al arrancar.
  # backend:
  #   image: izkybin/toolrent-backend:latest
  #   container_name: toolrent-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/toolrent
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #     - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/toolrent-realm
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     keycloak:
  #       condition: service_started
  #   networks:
  #     - toolrent-net

  # 4. Frontend (React + Nginx) - ¡COMENTAR TODO ESTO!
  # Razón: Lo correrás con 'npm run dev' para ver cambios en tiempo real.
  # frontend:
  #   image: izkybin/toolrent-frontend:latest
  #   container_name: toolrent-frontend
  #   ports:
  #     - "80:80"
  #   environment:
  #     - VITE_KEYCLOAK_URL=http://localhost:8090
  #     - VITE_KEYCLOAK_REALM=toolrent-realm
  #     - VITE_KEYCLOAK_CLIENT_ID=toolrent-client
  #   depends_on:
  #     - backend
  #   networks:
  #     - toolrent-net

volumes:
  db_data:

networks:
  toolrent-net:
    driver: bridge